---
title: 
author: 
date: 
output: html_document
---
Gathering Data:
```{r}
heartmortCOMPLETE = read.csv(file = "https://raw.githubusercontent.com/PDBoegel/HeartMortality/master/HeartMort.csv", header = TRUE)
heartmort = heartmortCOMPLETE[-c(1:4,7,24:26)] #Getting rid of variables for metadata and other dependent variable
options(max.print = 4000)
```

# Basic data manipulation to better fit normality assumptions for linear models

```{r}
heartmort$PCTPOPUNDER65 = heartmortCOMPLETE$PCTPOP30TO65 + heartmortCOMPLETE$PCTPOPUNDER30 # To account for elderly population
heartmort <- subset(heartmort, AVGINCOMEPERPERSON > 0 & PCTASIANAM != 0 & PCTAFRAM != 0 & PCTNATIVEAM != 0) # 26 counties had 0 avgincome/PCTAFRAM/PCTNATIVEAM/PCTASAINAM, removal should not affect study and makes histogram/log transform variables easier to make/use later
summaryOfVars <- summary(heartmort)
summaryOfVars
```
```{r, echo=FALSE}
heartmort <- heartmort[,c(1:6,14:16,19,7:13,18,20)] #Organization to make category variables easier later on. Does not need to go into document

heartmort[,c(7:19)] <- heartmort[,c(7:19)]/100 # Making percents into numbers [0,1]
```

```{r, results='hide'}
# We log totals imeediately as popsize varies widely from county to county
totCols <- c("LNTOTLOWEDU","LNTOTMEDEDU","LNTOTHIGHEDU","LNTOTOBESE","LNTOTDIABETES","LNTOTMALE","LNTOTFEMALE","LNTOTWHITE","LNTOTAFRAM","LNTOTASIANAM","LNTOTNATIVEAM","LNTOTUNEMPLOYED","LNTOTNONELDERLY")
heartmort[totCols] <- log(heartmort$POPSIZE * heartmort[7:19])

# Making categories for PCT variables
catCols <- c("CATHDMORTPERPERSON","CATLOWEDU","CATMEDEDU","CATHIGHEDU","CATOBESE","CATDIABETES","CATMALE","CATFEMALE","CATWHITE","CATAFRAM","CATASIANAM","CATNATIVEAM","CATUNEMPLOYED","CATNONELDERLY")
heartmort[catCols] <- 0
df <- lapply(c(2,7:19), function(i) cut(heartmort[,i], c(-.01, max(0, as.numeric(quantile(heartmort[,i], probs = 0.25)) - (1.5 * (as.numeric(quantile(heartmort[,i], probs = 0.75)) - as.numeric(quantile(heartmort[,i],probs = 0.25))))), min(1, as.numeric(quantile(heartmort[,i], probs = 0.75)) + (1.5 * as.numeric((quantile(heartmort[,i], probs = 0.75)) - as.numeric(quantile(heartmort[,i], probs = 0.25))))),1.01), right = FALSE, labels = c(0:2)))

heartmort[33:46] <- df
colnames(heartmort)[33:45] <- catCols
# Log transformations from what was specified above
logCols <- c("LNPOPSIZE","LNHDMORTPERPERSON","LNPOPDENSITY","LNHOUSINGUNITS","LNHOUSINGUNITSDENSITY","LNAVGINCOMEPERPERSON")
heartmort[logCols] <- log(heartmort[1:6])
par(mfrow = c(2,3))
```

**linear model analysis**

```{r}
attach(heartmort)
totlm = lm(LNHDMORTPERPERSON ~ LNTOTLOWEDU + LNTOTMEDEDU + LNTOTHIGHEDU + LNTOTAFRAM + LNTOTASIANAM + LNTOTDIABETES + LNTOTMALE + LNTOTNATIVEAM + LNTOTNONELDERLY + LNTOTOBESE + LNTOTUNEMPLOYED + LNTOTWHITE + LNPOPDENSITY + LNHOUSINGUNITSDENSITY + LNAVGINCOMEPERPERSON, data = heartmort)
summary(totlm)
```

```{r}
pctlm <- lm(LNHDMORTPERPERSON ~ log(LOWEDUCATION) + log(MEDEDUCATION) + log(HIGHEDUCATION) + log(PCTAFRAM) + log(PCTASIANAM) + log(PCTDIABETES) + log(PCTMALE) + log(PCTNATIVEAM) + log(PCTPOPUNDER65) + log(PCTOBESE) + log(PCTUNEMPLOYED) + log(PCTWHITE) + LNPOPDENSITY + LNHOUSINGUNITSDENSITY + LNAVGINCOMEPERPERSON, data = heartmort)
summary(pctlm)
```

```{r}
catlm = lm(LNHDMORTPERPERSON ~ factor(CATLOWEDU) + factor(CATMEDEDU) + factor(CATHIGHEDU) + LNTOTDIABETES + factor(CATMALE) + LNTOTNONELDERLY + LNTOTOBESE + LNTOTUNEMPLOYED + factor(CATWHITE) + LNPOPDENSITY + LNHOUSINGUNITSDENSITY + LNAVGINCOMEPERPERSON, data = heartmort)
summary(catlm)
```

```{r}
model <- lm(LNHDMORTPERPERSON ~ log(LOWEDUCATION) + log(MEDEDUCATION) + log(PCTAFRAM) + log(PCTASIANAM) + log(PCTDIABETES) + log(PCTMALE) + log(PCTPOPUNDER65) + log(PCTOBESE) + log(PCTWHITE) + LNPOPDENSITY + LNHOUSINGUNITSDENSITY, data = heartmort)
summary(model)
anova(model, pctlm)
```
**Sensitivity Analysis** 

```{r}
leverage = hatvalues(model) 

k = length(model$coefficients)-1
n = dim(heartmort)[1]
averagelev = (k+1)/n
hist(leverage, main="Histogram of Leverages", xlab = "Leverage", breaks = 15)
levs <-as.numeric(which(leverage > 3*averagelev))
heartmortNoLev = heartmort[-levs,]
modelNoLev <- lm(LNHDMORTPERPERSON ~ LNTOTHIGHEDU + LNTOTAFRAM + LNTOTASIANAM + LNTOTDIABETES + LNTOTMALE + LNTOTNATIVEAM + LNTOTNONELDERLY + LNTOTOBESE + LNTOTWHITE + LNPOPDENSITY + LNHOUSINGUNITSDENSITY, data = heartmortNoLev)
summary(modelNoLev)
```


**Model without high standardized residuals**
```{r}
hist(rstandard(model), main="Histogram of Standardized Residuals", xlab = "Standardized Residual")
resid = as.numeric(which(abs(rstandard(model)) > 2))

heartmortNoHighResid = heartmort[-resid,]
modelNoHighResid <- lm(LNHDMORTPERPERSON ~ LNTOTHIGHEDU + LNTOTAFRAM + LNTOTASIANAM + LNTOTDIABETES + LNTOTMALE + LNTOTNATIVEAM + LNTOTNONELDERLY + LNTOTOBESE + LNTOTWHITE + LNPOPDENSITY + LNHOUSINGUNITSDENSITY, data = heartmortNoHighResid)
summary(modelNoHighResid)
```


**Model without both high std residuals and leverage points**
```{r}
heartmortFinal = heartmort[c(-resid,-levs),]
modelFinal <- lm(LNHDMORTPERPERSON ~ log(LOWEDUCATION) + log(MEDEDUCATION) + log(PCTAFRAM) + log(PCTASIANAM) + log(PCTDIABETES) + log(PCTMALE) + log(PCTPOPUNDER65) + log(PCTOBESE) + log(PCTWHITE) + LNPOPDENSITY + LNHOUSINGUNITSDENSITY, data = heartmortFinal)
summary(modelFinal)
```


**End sensitivity analysis**

**Collinearity**

**Table of Correlations: Using PCT**
```{r, message=FALSE, warning=FALSE}
#Table of correlations : EDUCATION LEVEL AND OBESITY/DIABETES RATES
cor(heartmort[7:11])

#Table of correlations : Demographic
cor(heartmort[12:17])

#Table of correlations : Population, Housing, Income
cor(heartmort[c(1,3:6)])

library(faraway)
vif(modelFinal)
```

# Appendix

```{r, results='hide', echo=FALSE}
# Put These into the appendix
par(mfrow = c(2,3))
lapply(1:19, function(i) hist(heartmort[,i], xlab = names(heartmort)[i], main = paste("Histogram of", names(heartmort)[i])))
```
```{r, results='hide', echo=FALSE}
# Put these into the appendix
par(mfrow = c(2,3))
lapply(c(20:32,47:52), function(i) hist(heartmort[,i], xlab = names(heartmort)[i], main = paste("Histogram of", names(heartmort)[i]))) # This goes into the appendix
```

**Added Variable Plot**
```{r}
e1 = lm(LNHDMORTPERPERSON ~ log(LOWEDUCATION) + log(MEDEDUCATION) + log(PCTAFRAM) + log(PCTASIANAM) + log(PCTDIABETES) + log(PCTPOPUNDER65) + log(PCTOBESE) + log(PCTWHITE) + LNPOPDENSITY + LNHOUSINGUNITSDENSITY, data = heartmort)
e2 = model <- lm(log(PCTMALE) ~ log(LOWEDUCATION) + log(MEDEDUCATION) + log(PCTAFRAM) + log(PCTASIANAM) + log(PCTDIABETES) + log(PCTPOPUNDER65) + log(PCTOBESE) + log(PCTWHITE) + LNPOPDENSITY + LNHOUSINGUNITSDENSITY, data = heartmort)

e1resid = residuals(e1)
e2resid = residuals(e2)

plot(e1resid,e2resid,main = "Added Variable Plot")

abline(lm(e1resid ~ e2resid), col="red")
```

```{r}






```

